const FILTERS_ACTIONS = {
    SET_FULL_GENRE_LIST: "SET_FULL_GENRE_LIST",
    CHANGE_FILTER_TYPE: "CHANGE_FILTER_TYPE",
    ENTER_NAME_TO_SEARCH: "ENTER_NAME_TO_SEARCH",
    SELECT_SORT_BY: "SELECT_SORT_BY",
    SELECT_YEARS: "SELECT_YEARS",
    SELECT_GENRES: "SELECT_GENRES",
    RESET_FILTERS: "RESET_FILTERS",
  };
  
  const FILTER_TYPES = {
    BY_NAME: "BY_NAME",
    BY_SORT_BY: "BY_SORT_BY",
  };
  
  export { FILTERS_ACTIONS, FILTER_TYPES };